name: SSL Expiry Check

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight
  workflow_dispatch:   # Allow manual triggering

jobs:
  ssl_expiry_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bash
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl

      - name: Run SSL Expiry Check
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          DOMAINS: ${{ secrets.DOMAINS }}
        run: |
          ls -l
          chmod +x ssl_expiry.sh
          ./ssl_expiry.sh

